// Code generated by hertz generator.

package main

import (
	"github.com/ahang7/go-hello/cloudwego/hertz/biz_demo/hertz_gorm/biz/dal"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	dal.Init()
	h := server.Default()

	register(h)
	h.Spin()
}
