services:
  mysql:
    image: 'mysql:latest'
    container_name: tiktok_mysql
    volumes:
      - ./pkg/configs/sql:/docker-entrypoint-initdb.d
    ports:
      - "18000:3306"
    environment:
      - MYSQL_DATABASE=douyin
      - MYSQL_USER=douyin
      - MYSQL_PASSWORD=douyin123
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
    restart: always
    profiles:
      - dev
      - release