// Code generated by hertz generator.

package world

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SayHello .
// @router /hello [GET]
func SayHello(ctx context.Context, c *app.RequestContext) {
	var err error
	var req string
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(string)

	c.JSON(consts.StatusOK, resp)
}

// Bye .
// @router /bye [GET]
func Bye(ctx context.Context, c *app.RequestContext) {
	var err error
	var req string
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(string)

	c.JSON(consts.StatusOK, resp)
}
